FROM openjdk:17-jdk-slim

WORKDIR /app

COPY gradlew .
COPY gradle gradle

COPY . .

RUN chmod +x gradlew

RUN ./gradlew build -x test

CMD ["java", "-jar", "build/libs/ByteBridge-0.0.1-SNAPSHOT.jar"]